"""Supported aggregate for all Skill validation and guidance tests.

Behavior groups remain individually addressable through this script.
"""
import unittest

from skill_metadata_tests import SkillMetadataTests
from skill_resource_tests import SkillResourceMapTests
from skill_asset_tests import SkillAssetContractTests
from skill_ci_contract_tests import CiMaintenanceInputTests
from skill_canonical_tests import CanonicalSkillGuidanceTests
from skill_portability_tests import SkillPortabilityTests
from skill_project_map_tests import ProjectMapInputTests
from skill_placement_tests import InstalledSkillPlacementTests
from skill_guidance_tests import SkillGuidanceTests, ExplicitRecordingGuidanceTests
from skill_contract_tests import RecordingReferenceContractTests, RelocatedPlanSurfaceTests, CiAssemblyDeclarationTests
from skill_cli_tests import SkillCliTests
from skill_readability_guidance_tests import MarkdownReadabilityGuidanceTests
from skill_authority_tests import RetainedSkillAuthorityTests, ConsolidatedReviewGateSkillContractTests, RetireStandaloneTestSpecM3Tests, RetireStandaloneTestSpecM4Tests, RetireStandaloneTestSpecM5Tests
from skill_route_guidance_tests import RouteSkillCutoverContractTests
from skill_verify_guidance_tests import VerifySkillSimplificationContractTests, ExplainChangeSkillRetirementTests, FinalVerificationPackageParityM4Tests
from skill_pr_guidance_tests import PRSkillSimplificationTests
from skill_plan_guidance_tests import PlanSkillSimplificationContractTests
from skill_proposal_guidance_tests import ProposalSkillSimplificationTests
from skill_design_resource_tests import UnifiedDesignResourceTests
from skill_vision_guidance_tests import VisionSkillProgressiveDisclosureTests
from skill_learn_guidance_tests import LearnSkillSimplificationTests
from skill_project_map_guidance_tests import ProjectMapSkillSimplificationTests
from skill_ci_guidance_tests import CiMaintenanceSkillSimplificationTests
from skill_bugfix_guidance_tests import BugfixSkillSimplificationTests
from skill_shared_policy_tests import RequirementDeliveryModelM1Tests, RequirementDeliveryModelM2Tests, RequirementDeliveryModelM3Tests, ReviewCloseoutResourceTests, TestPolicyResourceTests
from skill_discovery_guidance_tests import OptionalDiscoverySkillContractTests


if __name__ == "__main__":
    unittest.main(verbosity=2)
