"""Supported aggregate for all Skill validation and guidance tests.

Behavior groups remain individually addressable through this script.
"""
import unittest

from skill_metadata_tests import SkillMetadataTests
from skill_resource_tests import SkillResourceMapTests
from skill_asset_tests import SkillAssetContractTests
from skill_ci_contract_tests import CiMaintenanceInputTests
from skill_canonical_tests import CanonicalSkillGuidanceTests
from skill_portability_tests import SkillPortabilityTests
from skill_project_map_tests import ProjectMapInputTests
from skill_guidance_tests import SkillGuidanceTests
from skill_contract_tests import CiAssemblyDeclarationTests, WorkflowRoleStageTests
from skill_cli_tests import SkillCliTests
from skill_vision_guidance_tests import VisionSkillProgressiveDisclosureTests
from skill_learn_guidance_tests import LearnSkillSimplificationTests
from skill_project_map_guidance_tests import ProjectMapSkillSimplificationTests
from skill_ci_guidance_tests import CiMaintenanceSkillSimplificationTests
from skill_bugfix_guidance_tests import BugfixSkillSimplificationTests
from skill_shared_policy_tests import RequirementDeliveryModelM3Tests, ReviewCloseoutResourceTests, TestPolicyResourceTests
from skill_discovery_guidance_tests import OptionalDiscoverySkillContractTests


if __name__ == "__main__":
    unittest.main(verbosity=2)
