import assert from "node:assert/strict";
import {test} from "node:test";
import {mkdtempSync,mkdirSync,readFileSync,writeFileSync,rmSync,unlinkSync,symlinkSync} from "node:fs";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {executeRecordStore} from "../dist/lib/record-store.js";
import {executeRecordingQueryCli} from "../dist/lib/recording-query-cli.js";
import {scanObservations,canonicalJSON} from "../dist/lib/recording-observations.js";
import {preparePrimaryReceipt,boundAdvancedObservations,validatePrimaryResult} from "../dist/lib/recording-result.js";
import {RecordFiles,digest} from "../dist/lib/record-store-files.js";
import {V2_FORMAT} from "../dist/lib/record-store-format.js";
const prefix="docs/changes/example/",mp=prefix+"change.json",rp=prefix+"reviews/design-review.json",ep=prefix+"evidence.json";
const enc=x=>JSON.stringify(x)+"\n";
const fixture=()=>JSON.parse(readFileSync(new URL("../../../tests/fixtures/rigorloop-records-v2/records.json",import.meta.url)));
function setup(t,version=2) {const root=mkdtempSync(join(tmpdir(),"recording-query-"));t.after(()=>rmSync(root,{recursive:true,force:true}));mkdirSync(join(root,"docs/changes"),{recursive:true});if(version)assert.equal(executeRecordStore({root,changeId:"example",operation:"record",request:fixture().request}).status,"saved");return root;}
function query(root,words,input,extra=[],options={}) {const x=executeRecordingQueryCli([...words,"--root",root,...(words[0]==="subject"?[]:["--change","example"]),"--format","json",...(input?["--input","-"]:[]),...extra],{...options,input:input?enc(input):undefined});validatePrimaryResult(x.result);return x.result;}
const context=(root,select,extra=[],detail)=>query(root,["context"],{schema_version:1,select,...(detail?{detail}:{})},extra);
const allKinds=["work","review","finding","blocker","evidence","decision","verify","decisions","model","proposal","plan","activity","applicability"];

test("TG-03 explicit context covers every kind without broad shallow expansion",t=>{const root=setup(t);for(const kind of allKinds){const r=context(root,[{kind,where:{}}]);assert.equal(r.status,"inspected",JSON.stringify(r));assert.equal(r.record_contract,"rigorloop-records-v2");assert.ok(r.revision);assert.ok(r.data.items.length>0,kind);assert.ok(r.data.items.every(x=>x.kind===kind));assert.ok(r.scope.complete);assert.equal(r.scope.total,r.data.items.length);}const r=context(root,[{kind:"finding",where:{}}]);assert.ok(r.data.items[0].fields.origin);assert.equal(r.data.items[0].origin_available,true);});

test("TG-03 all filters are literal AND/OR deduplicated and unknown_value rejects",t=>{const root=setup(t),f=fixture();const cases={work:{ids:["work-1"],status:["completed"]},review:{ids:["design-review"],target:[f.review.target],judgment:[f.review.judgment],subject_paths:[f.review.subjects[0].path]},finding:{ids:["finding-1"],review_ids:["design-review"],state:["resolved"],subject_paths:[f.review.findings[0].subjects[0].path]},blocker:{ids:["blocker-1"],state:["resolved"],subject_paths:[f.change.blockers[0].subjects[0].path]},evidence:{ids:["check-1"],result:["failed"],subject_paths:[f.evidence.checks[0].subjects[0].path]},decision:{ids:["decision-1"],subject_paths:[f.decisions.decisions[0].subjects[0].path]},model:{ids:["model-1"],subject_paths:[f.change.models[0].subject.path]},applicability:{paths:[rp],value:["current"]}};for(const [kind,where]of Object.entries(cases)){assert.equal(context(root,[{kind,where},{kind,where}]).data.items.length,1,kind);for(const key of Object.keys(where)){const bad={...where,[key]:[]};assert.equal(context(root,[{kind,where:bad}]).status,"rejected");}}for(const select of [[],[{kind:"unknown_value",where:{}}],[{kind:"work",where:{unknown_value:[]}}],[{kind:"work",where:{status:["unknown_value"]}}]])assert.equal(context(root,select).status,"rejected");});

test("TG-03 full show includes Verify and shared decisions; review context excludes findings",t=>{const root=setup(t);for(const kind of ["verify","decisions"]){const r=query(root,[kind,"show"]);assert.equal(r.data.items[0].fields.body,fixture()[kind].body);assert.equal(r.data.items[0].applicability.value,"current");assert.deepEqual(r.scope.omitted_fields,[]);}const r=query(root,["review","show","design-review"]);assert.equal(r.data.items[0].fields.findings.length,1);assert.deepEqual(r.scope.omitted_fields,[]);const c=context(root,[{kind:"review",where:{}}]);assert.equal(c.data.items[0].fields.findings,undefined);assert.deepEqual(c.scope.omitted_fields,[{kind:"review",fields:["findings"]}]);for(const [kind,id] of [["work","work-1"],["blocker","blocker-1"],["evidence","check-1"],["decision","decision-1"]])assert.equal(query(root,[kind,"show",id]).status,"inspected");assert.equal(query(root,["finding","show","finding-1"],undefined,["--review","design-review"]).status,"inspected");});

test("TG-03 summaries expose every omitted field including origin and narrative",t=>{const root=setup(t);for(const kind of ["work","review","finding","blocker","evidence","decision","verify","decisions"]){const full=context(root,[{kind,where:{}}]),summary=context(root,[{kind,where:{}}],[],"summary");const missing=Object.keys(full.data.items[0].fields).filter(k=>!Object.hasOwn(summary.data.items[0].fields,k));for(const field of missing)assert.ok(summary.scope.omitted_fields.find(x=>x.kind===kind).fields.includes(field));}assert.equal(context(root,[{kind:"finding",where:{}}],[],"summary").data.items[0].fields.origin,undefined);});

test("TG-03 missing selected content is unknown; unselected missing content does not change totals",t=>{const root=setup(t);unlinkSync(join(root,rp));const r=context(root,[{kind:"finding",where:{}}]);assert.equal(r.scope.total,null);assert.equal(r.scope.complete,false);assert.deepEqual(r.scope.missing_paths,[rp]);assert.equal(r.scope.next,null);assert.equal(context(root,[{kind:"work",where:{}}]).scope.total,1);const show=query(root,["review","show","design-review"]);assert.equal(show.errors[0].code,"broken-reference");assert.ok(show.observation_summary.by_code["missing-content"]);const status=query(root,["status"]);assert.equal(status.data.counts.findings.total,null);assert.equal(status.data.counts.reviews.known_total,0);assert.equal(status.scope.complete,false);});

test("TG-03 absent roots and null plan have distinct truthful representations",t=>{const absent=setup(t,0);for(const words of [["status"],["context"]]){const r=query(absent,words,words[0]==="context"?{schema_version:1,select:[{kind:"work",where:{}}]}:undefined);assert.equal(r.record_contract,null);assert.equal(r.revision,null);assert.equal(r.observation_summary.by_code["absent-change"],1);}assert.equal(query(absent,["verify","show"]).errors[0].code,"target-not-found");const root=setup(t);assert.equal(context(root,[{kind:"plan",where:{}}]).data.items[0].fields,null);});

test("TG-03 pagination binds normalized selection, exact last member and current revision",t=>{const root=setup(t),select=[{kind:"work",where:{}},{kind:"finding",where:{}},{kind:"evidence",where:{}}];let r=context(root,select,["--limit","1"]),items=[...r.data.items];while(r.scope.next){const n=r.scope.next;r=context(root,[...select].reverse(),["--limit","1","--after",n.token,"--expected-revision",n.expected_revision]);assert.equal(r.status,"inspected");items.push(...r.data.items);}assert.equal(items.length,3);const first=context(root,select,["--limit","1"]),n=first.scope.next;assert.equal(context(root,[{kind:"work",where:{}}],["--after",n.token,"--expected-revision",n.expected_revision]).errors[0].code,"invalid-cursor");assert.equal(context(root,select,["--after",n.token]).status,"rejected");writeFileSync(join(root,ep),enc({...fixture().evidence,checks:[]}));assert.equal(context(root,select,["--after",n.token,"--expected-revision",n.expected_revision]).status,"conflict");});

test("TG-03 byte limits never truncate first item or return a non-progressing page",t=>{const root=setup(t),r=JSON.parse(readFileSync(join(root,rp)));r.body="x".repeat(6000);writeFileSync(join(root,rp),enc(r));const full=context(root,[{kind:"review",where:{}}],["--max-bytes","4096"]);assert.equal(full.errors[0].code,"limit-exceeded");assert.equal(context(root,[{kind:"review",where:{}}],["--max-bytes","4096"],"summary").status,"inspected");assert.equal(query(root,["review","show","design-review"],undefined,["--max-bytes","4096"]).status,"rejected");});

test("TG-03 subject inspect hashes returned bytes and supports missing identity and streaming mode",t=>{const root=setup(t,0);writeFileSync(join(root,"basis"),"Exact 确认\n");const r=query(root,["subject","inspect"],undefined,["--path","basis","--path","missing","--content","full"]);assert.equal(r.status,"inspected");assert.equal(r.data.subjects[0].identity,digest(r.data.contents[0].content));assert.equal(r.data.subjects[1].identity,null);assert.equal(r.observations_scope,"selected-subjects");assert.equal(r.record_contract,undefined);const none=query(root,["subject","inspect"],undefined,["--path","basis"]);assert.equal(none.data.contents,undefined);symlinkSync(join(root,"basis"),join(root,"unsafe"));assert.equal(query(root,["subject","inspect"],undefined,["--path","unsafe"]).errors[0].code,"unsafe-path");});

test("TG-04 observation identity includes all observed subjects once, including retained origin",t=>{const root=setup(t);mkdirSync(join(root,"docs/proposals"),{recursive:true});writeFileSync(join(root,"docs/proposals/example.md"),"B");const r=query(root,["observations","show"],undefined,["--limit","1"]),n=r.scope.next;assert.ok(n);writeFileSync(join(root,"docs/proposals/example.md"),"C");const fresh=query(root,["observations","show"],undefined,["--limit","1"]);assert.equal(fresh.revision,r.revision);assert.notEqual(fresh.scope.observation_identity,r.scope.observation_identity);assert.equal(query(root,["observations","show"],undefined,["--after",n.token,"--expected-revision",n.expected_revision,"--expected-observations",n.expected_observations]).status,"conflict");});

test("TG-04 digest canonicalization and subject dedup agree with exact preimage",t=>{const root=setup(t),set=Object.fromEntries(fixture().request.writes.map(w=>[w.path,w.content])),reader=new RecordFiles(root),counts=new Map(),hash=reader.hash.bind(reader);reader.hash=p=>{counts.set(p,(counts.get(p)??0)+1);return hash(p);};const scan=scanObservations({set,format:V2_FORMAT,reader,revision:"sha256:"+"a".repeat(64)});const diagnostics=[...scan.diagnostics()];assert.equal(scan.identity,digest(canonicalJSON({schema_version:2,revision:"sha256:"+"a".repeat(64),observed_subjects:scan.subjects,observations:diagnostics})));assert.ok([...counts.values()].every(n=>n===1));assert.equal(canonicalJSON({z:{b:1,a:2},a:0}),'{"a":0,"z":{"a":2,"b":1}}');});

test("TG-04 maximum receipt counters and changed targets fit reserve; details overflow is explicit",()=>{const changed=Array.from({length:128},(_,i)=>({kind:"applicability",target:{path:'"'.repeat(1000)+i}}));const summary={scope:"registered-snapshot",total:2147483647,by_code:{"absent-change":0,"subject-drift":2147483647,"failed-evidence":0,"inconsistent-claim":0,"missing-content":0},details_included:false,observation_identity:"sha256:"+"a".repeat(64)};const r=preparePrimaryReceipt({operation:"batch",status:"saved",change_id:"x".repeat(80),revision:"sha256:"+"a".repeat(64),changed,observation_summary:summary,details:{files:[],effects:[{operation_index:0,path:"basis",target:{},changed_fields:["x".repeat(9*1024*1024)],bookkeeping:false}]}});assert.ok(Buffer.byteLength(r.json)<512*1024);assert.deepEqual(r.result.details,{included:false,reason:"response-limit"});assert.match(r.human,/storage-only/);});

test("TG-04 advanced diagnostic expansion uses bounded truthful aggregate",()=>{function* observations(){for(let i=0;i<12000;i++)yield{code:"subject-drift",path:'"'.repeat(1000)+i,message:"Record store: subject-drift."};}const result=boundAdvancedObservations(observations(),1024*1024);assert.equal(result.length,1);assert.equal(result[0].path,null);assert.match(result[0].message,/12000.*omitted/);assert.throws(()=>boundAdvancedObservations([{code:"unknown_value",path:null,message:"bad"}],100));});

test("TG-03 cursor filter normalization sorts JSON-encoded values",t=>{const root=setup(t);const r=context(root,[{kind:"review",where:{subject_paths:['"','A']}}]);assert.deepEqual(r.scope.select[0].where.subject_paths,['A','"']);});

test("TG-03 overlapping snapshot failures do not expose unverified revision or observations",t=>{const root=setup(t);const r=query(root,["status"],undefined,[],{fault:p=>{if(p==="during-inspect")writeFileSync(join(root,ep),enc({...fixture().evidence,checks:[]}));}});assert.equal(r.status,"conflict");assert.equal(r.revision,undefined);assert.equal(r.observation_summary,undefined);});

test("TG-04 mutation receipts are precomputed by shared persistence and reconstruct observations",async t=>{const {primaryReceiptPreparer}=await import("../dist/lib/recording-result.js");const root=setup(t,0),request=fixture().request;const output=executeRecordStore({root,changeId:"example",operation:"record",request},{prepareResult:primaryReceiptPreparer({operation:"batch",changeId:"example",changed:[{kind:"work",target:{id:"work-1"}}]})});assert.equal(output.result.status,"saved");assert.ok(Buffer.byteLength(output.json)<512*1024);assert.ok(Buffer.byteLength(output.human)<512*1024);const observations=query(root,["observations","show"]);assert.equal(output.result.observation_summary.observation_identity,observations.scope.observation_identity);assert.equal(executeRecordStore({root,changeId:"example",operation:"record",request}).status,"conflict");});

test("TG-03 unsafe paths retain unsafe-path through selector-schema unions",t=>{const root=setup(t);for(const [kind,key]of [["review","subject_paths"],["applicability","paths"]])assert.equal(context(root,[{kind,where:{[key]:["../secret"]}}]).errors[0].code,"unsafe-path");});

test("TG-03 every query selector fails before filesystem and stdin on malformed arguments",()=>{let read=false;for(const words of [["context","--input","-","--limit","0"],["context","--input","-","--unknown","secret"],["verify","show","extra"],["status","--after","secret"],["finding","show","f"],["subject","inspect","--path","../secret"]]){const x=executeRecordingQueryCli([...words,"--root","/does-not-exist","--change","example","--format","json"],{readInput:()=>{read=true;throw new Error();}});assert.equal(x.result.status,"rejected");assert.equal(read,false);assert.equal((x.json+x.human).includes("secret"),false);}const x=executeRecordingQueryCli(["context","--help"],{readInput:()=>{throw new Error();}});assert.equal(x.exitCode,0);});

test("TG-03 malformed nonmember cursor keys reject without partial items",t=>{const root=setup(t),select=[{kind:"work",where:{}},{kind:"evidence",where:{}}],first=context(root,select,["--limit","1"]),n=first.scope.next;const decoded=JSON.parse(Buffer.from(n.token,"base64url"));for(const mutate of [x=>x.extra=true,x=>x.version=99,x=>x.last.target={id:"missing"},x=>x.last={path:mp,kind:"unknown_value",target:{}}]){const c=structuredClone(decoded);mutate(c);const token=Buffer.from(JSON.stringify(c)).toString("base64url");const r=context(root,select,["--after",token,"--expected-revision",n.expected_revision]);assert.equal(r.errors[0].code,"invalid-cursor");assert.equal(r.data,undefined);}assert.equal(context(root,select,["--after","bad=","--expected-revision",n.expected_revision]).errors[0].code,"invalid-cursor");});

test("TG-04 digest follows silent and retained-origin subjects, excludes body and EntryRef strings",t=>{const root=setup(t),f=fixture(),set=Object.fromEntries(f.request.writes.map(w=>[w.path,w.content]));writeFileSync(join(root,"silent"),"A");writeFileSync(join(root,"origin-only"),"B");const ev=JSON.parse(set[ep]);ev.checks[0].subjects=[{path:"silent",identity:digest("A")}];set[ep]=enc(ev);const review=JSON.parse(set[rp]);review.findings[0].origin.supporting_judgment.subjects=[{path:"origin-only",identity:digest("B")}];review.body='{"path":"body-only","identity":"sha256:fake"}';set[rp]=enc(review);const scan=()=>scanObservations({set,format:V2_FORMAT,reader:new RecordFiles(root),revision:digest("same")});const a=scan();assert.ok(a.subjects.some(s=>s.path==="origin-only"));assert.ok(!a.subjects.some(s=>s.path==="body-only"));writeFileSync(join(root,"silent"),"C");assert.notEqual(scan().identity,a.identity);const b=scan();unlinkSync(join(root,"origin-only"));assert.notEqual(scan().identity,b.identity);const absent=scan();writeFileSync(join(root,"origin-only"),"D");assert.notEqual(scan().identity,absent.identity);});

test("TG-04 unsafe or unreadable stored subjects never become null absence",t=>{const root=setup(t),r=JSON.parse(readFileSync(join(root,rp)));r.subjects=[{path:"unsafe-subject",identity:digest("x")}];writeFileSync(join(root,rp),enc(r));symlinkSync(join(root,ep),join(root,"unsafe-subject"));assert.equal(query(root,["status"]).errors[0].code,"unsafe-path");const hash=RecordFiles.prototype.hash;RecordFiles.prototype.hash=function(path){if(path==="unsafe-subject")throw Object.assign(new Error("private"),{code:"EACCES"});return hash.call(this,path);};try{assert.equal(query(root,["status"]).errors[0].code,"io-failure");}finally{RecordFiles.prototype.hash=hash;}});

test("TG-03 subject byte limits stop before reading later subjects and observed drift conflicts",t=>{const root=setup(t,0);writeFileSync(join(root,"large"),"x".repeat(4090));writeFileSync(join(root,"later"),"y");const read=RecordFiles.prototype.read;let later=false;RecordFiles.prototype.read=function(path,...args){if(path==="later")later=true;return read.call(this,path,...args);};try{assert.equal(query(root,["subject","inspect"],undefined,["--path","large","--path","later","--content","full","--max-bytes","4096"]).errors[0].code,"limit-exceeded");assert.equal(later,false);}finally{RecordFiles.prototype.read=read;}RecordFiles.prototype.read=function(){throw Object.assign(new Error("changed"),{recordStoreCode:"identity-conflict"});};try{const r=query(root,["subject","inspect"],undefined,["--path","large","--content","full"]);assert.equal(r.status,"conflict");assert.equal(r.data,undefined);}finally{RecordFiles.prototype.read=read;}});

test("TG-03 internal subprocess interface preserves JSON/text scope and outcomes",async t=>{const {spawnSync}=await import("node:child_process");const root=setup(t);const launcher=new URL("./helpers/recording-query-launcher.mjs",import.meta.url);for(const words of [["status"],["verify","show"],["context","--input","-"],["subject","inspect","--path","absent"]]){const args=[launcher.pathname,...words,"--root",root,...(words[0]==="subject"?[]:["--change","example"])],options={encoding:"utf8",input:enc({schema_version:1,select:[{kind:"finding",where:{}}]})};const j=spawnSync(process.execPath,[...args,"--format","json"],options),h=spawnSync(process.execPath,[...args,"--format","text"],options);assert.equal(j.status,0,j.stderr);assert.equal(h.status,0,h.stderr);assert.deepEqual(JSON.parse(h.stdout.slice(h.stdout.indexOf("{"))),JSON.parse(j.stdout));} });

test("TG-04 primary result closed vocabularies reject unknown_value and nested extras",t=>{const root=setup(t),good=query(root,["status"]);for(const field of ["operation","status","claim","record_contract"]){const bad=structuredClone(good);bad[field]="unknown_value";assert.throws(()=>validatePrimaryResult(bad),field);}for(const edit of [r=>r.scope.view="unknown_value",r=>r.data.counts.work.by_value.unknown_value=0,r=>r.data.activity.status="unknown_value",r=>r.observation_summary.by_code.unknown_value=0,r=>r.observation_summary.scope="unknown_value",r=>r.unknown_value=true]){const bad=structuredClone(good);edit(bad);assert.throws(()=>validatePrimaryResult(bad));}const found=context(root,[{kind:"finding",where:{}}]);for(const edit of [r=>r.data.items[0].kind="unknown_value",r=>r.scope.detail="unknown_value",r=>r.data.items[0].fields.state="unknown_value",r=>r.data.items[0].fields.origin=null]){const bad=structuredClone(found);edit(bad);assert.throws(()=>validatePrimaryResult(bad));}});

test("TG-04 dense failed evidence remains recordable after completion with bounded receipt",async t=>{const {primaryReceiptPreparer}=await import("../dist/lib/recording-result.js");const root=setup(t,0),f=fixture();f.evidence.checks=Array.from({length:1500},(_,i)=>({...f.evidence.checks[0],id:`check-${i}`}));const request=structuredClone(f.request);request.writes.find(w=>w.path===ep).content=enc(f.evidence);const output=executeRecordStore({root,changeId:"example",operation:"record",request},{prepareResult:primaryReceiptPreparer({operation:"batch",changeId:"example",changed:[{kind:"evidence",target:{id:"check-0"}}]})});assert.equal(output.result.status,"saved");assert.ok(output.result.observation_summary.total>=1500);assert.ok(Buffer.byteLength(output.json)<512*1024);const page=query(root,["observations","show"],undefined,["--limit","5"]);assert.equal(page.scope.returned,5);assert.equal(page.scope.complete,false);assert.equal(page.scope.observation_identity,output.result.observation_summary.observation_identity);});

test("TG-04 preview and unchanged receipts retain correct revisions; invalid rendering never publishes",async t=>{const {primaryReceiptPreparer}=await import("../dist/lib/recording-result.js");const root=setup(t,0),request=fixture().request,prepareResult=primaryReceiptPreparer({operation:"batch",changeId:"example",changed:[{kind:"work",target:{id:"work-1"}}]});const preview=executeRecordStore({root,changeId:"example",operation:"check",request},{prepareResult});assert.equal(preview.result.status,"valid");assert.equal(preview.result.revision,null);assert.ok(preview.result.candidate_revision);assert.equal(preview.result.observation_summary.scope,"candidate-snapshot");assert.equal(query(root,["status"]).revision,null);const invalid=executeRecordStore({root,changeId:"example",operation:"record",request},{prepareResult:primaryReceiptPreparer({operation:"unknown_value",changeId:"example",changed:[]})});assert.equal(invalid.status,"rejected");assert.equal(query(root,["status"]).revision,null);const saved=executeRecordStore({root,changeId:"example",operation:"record",request},{prepareResult});const inspect=executeRecordStore({root,changeId:"example",operation:"inspect"});request.expected_revision=inspect.revision;for(const w of request.writes)w.expected_identity=inspect.files.find(x=>x.path===w.path).identity;const unchanged=executeRecordStore({root,changeId:"example",operation:"record",request},{prepareResult});assert.equal(unchanged.result.status,"unchanged");assert.deepEqual(unchanged.result.changed,[]);assert.equal(saved.result.revision,unchanged.result.revision);});

test("TG-03 primary busy, recovery-required and verified conflict carry exact envelopes",t=>{const root=setup(t),lock=join(root,".rigorloop/record-store/example/lock");writeFileSync(lock,enc({pid:process.pid}));const busy=query(root,["status"]);assert.equal(busy.status,"busy");assert.equal(busy.revision,undefined);assert.equal(busy.transaction,undefined);unlinkSync(lock);const conflict=context(root,[{kind:"work",where:{}}],["--expected-revision",digest("stale")]);assert.equal(conflict.status,"conflict");assert.ok(conflict.revision);assert.ok(conflict.observation_summary);const absent=setup(t,0);const interrupted=executeRecordStore({root:absent,changeId:"example",operation:"record",request:fixture().request},{fault:p=>p==="after-preparation"?"crash":undefined});assert.equal(interrupted.status,"recovery-required");const recovery=query(absent,["status"]);assert.equal(recovery.status,"recovery-required");assert.deepEqual(recovery.transaction,interrupted.transaction);assert.equal(recovery.revision,undefined);assert.equal(recovery.record_contract,undefined);});

test("TG-04 primary save performs no fallible receipt reads after commit; lost response stays saved",async t=>{const {primaryReceiptPreparer}=await import("../dist/lib/recording-result.js");const root=setup(t,0),request=fixture().request;const hash=RecordFiles.prototype.hash;let committed=false,late=0;RecordFiles.prototype.hash=function(path,...args){if(committed&&!path.startsWith(".rigorloop/")){late++;throw Object.assign(new Error("late diagnostic read"),{code:"EACCES"});}return hash.call(this,path,...args);};let output;try{output=executeRecordStore({root,changeId:"example",operation:"record",request},{prepareResult:primaryReceiptPreparer({operation:"batch",changeId:"example",changed:[]}),fault:p=>{if(p==="after-commit")committed=true;}});}finally{RecordFiles.prototype.hash=hash;}assert.equal(output.result.status,"saved");assert.equal(late,0);assert.throws(()=>{throw Object.assign(new Error("lost output"),{code:"EPIPE"});});assert.equal(query(root,["status"]).revision,output.result.revision);assert.equal(executeRecordStore({root,changeId:"example",operation:"record",request}).status,"conflict");});

test("TG-04 observation cursor continuation and absent binding fail closed",t=>{const root=setup(t),first=query(root,["observations","show"],undefined,["--limit","1"]),next=first.scope.next;const args=["--expected-revision",next.expected_revision,"--expected-observations",next.expected_observations];const second=query(root,["observations","show"],undefined,[...args,"--after",next.token,"--limit","1"]);assert.equal(second.status,"inspected");assert.notDeepEqual(second.data.observations,first.data.observations);for(const edit of [c=>c.offset=999999,c=>c.version=2,c=>c.unknown_value=true]){const c=JSON.parse(Buffer.from(next.token,"base64url"));edit(c);assert.equal(query(root,["observations","show"],undefined,[...args,"--after",Buffer.from(enc(c).trim()).toString("base64url")]).errors[0].code,"invalid-cursor");}assert.equal(query(root,["observations","show"],undefined,["--expected-revision",next.expected_revision]).errors[0].code,"invalid-input");const absent=setup(t,0),a=query(absent,["observations","show"]);assert.equal(query(absent,["observations","show"],undefined,["--expected-revision","absent","--expected-observations",a.scope.observation_identity]).status,"inspected");});
