import assert from 'node:assert/strict';
import {test} from 'node:test';
import {spawnSync} from 'node:child_process';
import {mkdtempSync,mkdirSync,readFileSync,writeFileSync,rmSync,symlinkSync,renameSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {executeWorkflowContext,validateWorkflowContextResult} from '../dist/lib/workflow-context.js';
import {executeRecordStore} from '../dist/lib/record-store.js';
const cli=new URL('../dist/bin/rigorloop.js',import.meta.url).pathname;
const initial=JSON.parse(readFileSync(new URL('../../../tests/fixtures/rigorloop-records-v2/storage-safety.json',import.meta.url))).request;
function setup(t){const root=mkdtempSync(join(tmpdir(),'context-v2-'));t.after(()=>rmSync(root,{recursive:true,force:true}));mkdirSync(join(root,'.git'));mkdirSync(join(root,'docs/changes'),{recursive:true});return root;}
function request(id='example'){const r=JSON.parse(JSON.stringify(initial).replaceAll('example',id));r.reads=[];return r;}
function create(root,id='example'){const r=executeRecordStore({root,changeId:id,operation:'record',request:request(id)});assert.equal(r.status,'saved');return r;}
const context=(root,args=[])=>executeWorkflowContext([...args,'--json'],{cwd:root});
const directory=(root,id)=>{const p=join(root,'docs/changes',id);mkdirSync(p,{recursive:true});return p;};
test('factual v2 candidates have exact current revisions and no implicit selection or readiness',t=>{const root=setup(t),saved=create(root),r=context(root);assert.equal(r.exitCode,0);assert.deepEqual(Object.keys(r.result).sort(),['schema_version','command','status','configuration','locations','selection','candidates','scope','errors'].sort());assert.deepEqual(r.result.selection,{requested_change:null});assert.deepEqual(r.result.candidates,[{change_id:'example',path:'docs/changes/example/change.json',record_contract:'rigorloop-records-v2',revision:saved.revision}]);assert.equal(r.result.scope.complete,true);create(root,'aaa');assert.deepEqual(context(root).result.candidates.map(c=>c.change_id),['aaa','example']);});
test('explicit selection bypasses unrelated malformed candidates and absent selection stays absent',t=>{const root=setup(t);create(root);writeFileSync(join(directory(root,'bad'),'change.json'),'{broken');assert.equal(context(root).exitCode,2);const r=context(root,['--change','example']);assert.equal(r.exitCode,0);assert.deepEqual(r.result.selection,{requested_change:'example'});assert.equal(r.result.scope.inspected_directories,1);assert.deepEqual(context(root,['--change','absent']).result.candidates,[]);});
for(const shape of ['mixed','unknown_value','version-mismatch','malformed','missing-registered','residue','review-residue'])test(`classifier reports ${shape} without archive fallback`,t=>{const root=setup(t),p=directory(root,'example');let code='invalid-input';if(shape==='mixed'){writeFileSync(join(p,'change.json'),'{}');writeFileSync(join(p,'change.yaml'),'archive');}if(shape==='unknown_value'||shape==='version-mismatch'){writeFileSync(join(p,'change.json'),JSON.stringify({contract:shape==='unknown_value'?'unknown_value':'rigorloop-records-v2',schema_version:1})+'\n');code='unsupported-contract';}if(shape==='malformed')writeFileSync(join(p,'change.json'),'{private invalid');if(shape==='missing-registered'){const c=JSON.parse(request().writes[0].content);c.records=[{path:'docs/changes/example/evidence.json',kind:'evidence'}];c.applicability=[{path:c.records[0].path,value:'current',actor:{id:'a',role:'implement'},reason:'Fixture'}];writeFileSync(join(p,'change.json'),JSON.stringify(c)+'\n');}if(shape==='residue'){writeFileSync(join(p,'change.yaml'),'archive');writeFileSync(join(p,'evidence.json'),'{}');}if(shape==='review-residue'){mkdirSync(join(p,'reviews'));writeFileSync(join(p,'reviews/review.json'),'{}');}const r=context(root);assert.equal(r.exitCode,2);assert.equal(r.result.scope.complete,false);assert.equal(r.result.candidates.length,0);assert.equal(r.result.errors[0].code,code);assert.doesNotMatch(JSON.stringify(r.result),/private invalid/);});
test('archives and non-current directories are excluded without decoding',t=>{const root=setup(t);writeFileSync(join(directory(root,'archive'),'change.yaml'),'not: [valid');directory(root,'notes');const r=context(root);assert.equal(r.exitCode,0);assert.equal(r.result.scope.excluded_noncurrent,2);assert.equal(context(root,['--change','archive']).result.errors[0].code,'unsupported-contract');assert.equal(context(root,['--change','notes']).result.errors[0].code,'invalid-input');});
for(const count of [63,64,65])test(`candidate limit ${count} is inclusive at 64`,t=>{const root=setup(t);for(let i=0;i<count;i++){const id='c'+String(i).padStart(3,'0'),p=directory(root,id);writeFileSync(join(p,'change.json'),request(id).writes[0].content);}const r=context(root);assert.equal(r.exitCode,count>64?2:0);assert.equal(r.result.scope.complete,count<=64);if(count>64)assert.equal(r.result.errors[0].code,'limit-exceeded');else assert.equal(r.result.candidates.length,count);});
for(const count of [1023,1024,1025])test(`directory limit ${count} is inclusive at 1024`,t=>{const root=setup(t);for(let i=0;i<count;i++)directory(root,'n'+i);const r=context(root);assert.equal(r.exitCode,count>1024?2:0);if(count<=1024)assert.equal(r.result.scope.inspected_directories,count);else{assert.equal(r.result.scope.complete,false);assert.equal(r.result.errors[0].code,'limit-exceeded');}});
test('v2 exclusion and pending recovery report errors without writing or recovering',t=>{const root=setup(t);let observed;const r=executeRecordStore({root,changeId:'example',operation:'record',request:request()},{fault:p=>{if(p==='after-preparation'){observed=context(root,['--change','example']);return 'crash';}}});assert.equal(r.status,'recovery-required');const journal=join(root,'.rigorloop/record-store/example/journal.json'),before=readFileSync(journal);const pending=context(root,['--change','example']);assert.equal(pending.exitCode,2);assert.equal(pending.result.errors[0].code,'recovery-needed');assert.deepEqual(readFileSync(journal),before);assert.equal(observed.result.errors[0].code,'store-busy');});
test('configuration preserves non-record overrides and fixed v2 record locations',t=>{const root=setup(t);writeFileSync(join(root,'rigorloop.workflow.yaml'),'schema_version: 1\nartifact_locations:\n  plan:\n    path_template: planning/<change-id>.md\n');const r=context(root);assert.equal(r.exitCode,0);assert.deepEqual(r.result.locations.plan,{path_template:'planning/<change-id>.md',owner:'plan',provenance:'repository-override'});assert.equal(r.result.locations['change-record'].path_template,'docs/changes/<change-id>/change.json');assert.equal(r.result.locations['review-resolution'],undefined);});
for(const override of ['  change-record:\n    path_template: docs/changes/<change-id>/change.yaml','  review-resolution:\n    path_template: docs/resolution.md','  unknown_value:\n    path_template: docs/x.md','  plan:\n    path_template: ../escape','  plan:\n    path_template: docs/<unknown_value>.md','  plan:\n    path_template: docs/plan.md\n    owner: verify'])test('invalid configuration rejects with no advertised locations: '+override.split('\n')[0].trim(),t=>{const root=setup(t);writeFileSync(join(root,'rigorloop.workflow.yaml'),'schema_version: 1\nartifact_locations:\n'+override+'\n');const r=context(root);assert.equal(r.exitCode,2);assert.equal(r.result.configuration,null);assert.deepEqual(r.result.locations,{});});
test('unsafe enumeration and configuration sources reject without following symlinks',t=>{const root=setup(t),outside=join(root,'outside');mkdirSync(outside);symlinkSync(outside,join(root,'docs/changes/linked'));assert.equal(context(root).result.errors[0].code,'unsafe-path');rmSync(join(root,'docs/changes/linked'));writeFileSync(join(outside,'config'),'schema_version: 1');symlinkSync(join(outside,'config'),join(root,'rigorloop.workflow.yaml'));assert.equal(context(root).result.errors[0].code,'unsafe-path');});
test('human and JSON public output share facts and reject mutation flags without payload disclosure',t=>{const root=setup(t);create(root);const run=args=>spawnSync(process.execPath,[cli,'workflow-context',...args],{cwd:root,encoding:'utf8'});const json=run(['--json']),human=run(['--format','human']);assert.equal(json.status,0);assert.equal(human.status,0);assert.match(human.stdout,/complete=true/);assert.match(human.stdout,/Candidate example/);assert.doesNotMatch(json.stdout+human.stdout,new RegExp(root));const invalid=run(['--json','--mutate','private-value']);assert.equal(invalid.status,2);assert.doesNotMatch(invalid.stdout,/private-value/);});

for(const delta of [-1,0,1])test(`response budget boundary offset ${delta}`,t=>{
 const r=context(setup(t)).result,target=8*1024*1024+delta;
 r.locations.plan.path_template='x';
 const length=Buffer.byteLength(JSON.stringify(r))+1;
 r.locations.plan.path_template+='x'.repeat(target-length);
 assert.equal(Buffer.byteLength(JSON.stringify(r))+1,target);
 if(delta>0)assert.throws(()=>validateWorkflowContextResult(r),e=>e.recordStoreCode==='limit-exceeded');else assert.doesNotThrow(()=>validateWorkflowContextResult(r));
});
test('unknown_value public envelope vocabularies reject before consistency',t=>{
 const valid=context(setup(t)).result;
 for(const change of [r=>r.status='unknown_value',r=>r.scope.mode='unknown_value',r=>r.command='unknown_value',r=>r.locations.plan.owner='unknown_value',r=>r.locations.plan.provenance='unknown_value',r=>r.extra=true,r=>r.scope.extra=true,r=>r.errors=[{code:'unknown_value',path:null,message:'fixed'}]]){const r=structuredClone(valid);change(r);assert.throws(()=>validateWorkflowContextResult(r));}
});

test('unsafe or unknown_value command selectors reject before repository access',()=>{for(const args of [['--change','../private'],['--change','UPPERCASE'],['--format','unknown_value'],['--change'],['--json','--json']]){const r=executeWorkflowContext(args,{beforeRepositoryRead:()=>assert.fail('must not read')});assert.equal(r.exitCode,2);assert.equal(r.result.errors[0].code,'invalid-input');assert.doesNotMatch(JSON.stringify(r.result),/private|UPPERCASE|unknown_value/);}});

test('explicit non-record placement retains unresolved and duplicate ownership rejection',t=>{const root=setup(t);for(const template of ['docs/proposals/<change-id>.md','planning/<stage>.md']){writeFileSync(join(root,'rigorloop.workflow.yaml'),'schema_version: 1\nartifact_locations:\n  plan:\n    path_template: '+template+'\n');const r=context(root,['--change','example']);assert.equal(r.exitCode,2);assert.equal(r.result.errors[0].code,'invalid-input');}});
test('multiple invalid IDs return one redacted public diagnostic instead of an internal exception',t=>{
 const root=setup(t);directory(root,'BAD');directory(root,'OTHER');
 const r=spawnSync(process.execPath,[cli,'workflow-context','--json'],{cwd:root,encoding:'utf8'});
 assert.equal(r.status,2,r.stdout+r.stderr);const result=JSON.parse(r.stdout);
 assert.equal(result.schema_version,2);assert.equal(result.status,'rejected');assert.equal(result.scope.complete,false);
 assert.deepEqual(result.errors,[{code:'invalid-input',path:null,message:'Workflow context: invalid-input.'}]);
 assert.doesNotMatch(r.stdout+r.stderr,/BAD|OTHER|duplicate identity|internal-error/);
});
